const wines = [
  {
    name: "Chateau Lafite Rothschild",
    category: "Red",
    year: 2015,
    region: "Bordeaux",
    winery: "Chateau Lafite Rothschild",
    description:
      "A rich and complex wine with notes of dark fruits, cedar, and tobacco. Full-bodied with a long finish.",
    tags: ["rich", "dark fruits", "complex", "full-bodied"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 400,
    img: "https://example.com/images/chateau-lafite-rothschild.jpg",
    linkToPurchase: "https://example.com/purchase/chateau-lafite-rothschild",
  },
  {
    name: "Domaine de la Romanee-Conti",
    category: "Red",
    year: 2017,
    region: "Burgundy",
    winery: "Domaine de la Romanee-Conti",
    description:
      "A highly sought-after wine with elegant aromas of red berries, earth, and spice. Silky texture and refined tannins.",
    tags: ["elegant", "red berries", "earthy", "silky"],
    criticScore: 99,
    grape: "Pinot Noir",
    avgPrice: 2000,
    img: "https://example.com/images/domaine-de-la-romanee-conti.jpg",
    linkToPurchase: "https://example.com/purchase/domaine-de-la-romanee-conti",
  },
  {
    name: "Chateau d'Yquem",
    category: "Dessert",
    year: 2013,
    region: "Sauternes",
    winery: "Chateau d'Yquem",
    description:
      "An exquisite dessert wine with flavors of honey, apricot, and vanilla. Rich and sweet with a vibrant acidity.",
    tags: ["honey", "apricot", "vanilla", "rich", "sweet"],
    criticScore: 98,
    grape: "Semillon",
    avgPrice: 500,
    img: "https://example.com/images/chateau-d-yquem.jpg",
    linkToPurchase: "https://example.com/purchase/chateau-d-yquem",
  },

  {
    name: "Cloudy Bay Sauvignon Blanc",
    category: "White",
    year: 2020,
    region: "Marlborough",
    winery: "Cloudy Bay",
    description:
      "A vibrant and refreshing wine with aromas of citrus, passion fruit, and grass. Crisp acidity and mineral finish.",
    tags: ["citrus", "passion fruit", "grass", "vibrant", "refreshing"],
    criticScore: 92,
    grape: "Sauvignon Blanc",
    avgPrice: 30,
    img: "https://example.com/images/cloudy-bay-sauvignon-blanc.jpg",
    linkToPurchase: "https://example.com/purchase/cloudy-bay-sauvignon-blanc",
  },
  {
    name: "Chateau Ste. Michelle Eroica Riesling",
    category: "White",
    year: 2019,
    region: "Columbia Valley",
    winery: "Chateau Ste. Michelle",
    description:
      "A delicate and aromatic wine with flavors of peach, lime, and mineral. Off-dry with a crisp finish.",
    tags: ["peach", "lime", "mineral", "delicate", "off-dry"],
    criticScore: 91,
    grape: "Riesling",
    avgPrice: 20,
    img: "https://example.com/images/chateau-ste-michelle-eroica-riesling.jpg",
    linkToPurchase:
      "https://example.com/purchase/chateau-ste-michelle-eroica-riesling",
  },
  {
    name: "Whispering Angel Rose",
    category: "Rose",
    year: 2021,
    region: "Provence",
    winery: "Chateau d'Esclans",
    description:
      "A light and elegant rose with notes of strawberry, peach, and citrus. Dry with a refreshing finish.",
    tags: ["strawberry", "peach", "citrus", "light", "elegant"],
    criticScore: 93,
    grape: "Grenache",
    avgPrice: 25,
    img: "https://example.com/images/whispering-angel-rose.jpg",
    linkToPurchase: "https://example.com/purchase/whispering-angel-rose",
  },
  {
    name: "Inniskillin Icewine",
    category: "Dessert",
    year: 2017,
    region: "Niagara Peninsula",
    winery: "Inniskillin",
    description:
      "A luscious and sweet icewine with flavors of honey, apricot, and lychee. Balanced acidity and long finish.",
    tags: ["honey", "apricot", "lychee", "luscious", "sweet"],
    criticScore: 94,
    grape: "Vidal Blanc",
    avgPrice: 50,
    img: "https://example.com/images/inniskillin-icewine.jpg",
    linkToPurchase: "https://example.com/purchase/inniskillin-icewine",
  },
  {
    name: "Veuve Clicquot Brut Yellow Label",
    category: "Sparkling",
    year: 2012,
    region: "Champagne",
    winery: "Veuve Clicquot",
    description:
      "A classic champagne with aromas of apple, pear, and toast. Fine bubbles and a rich, creamy texture.",
    tags: ["apple", "pear", "toast", "creamy", "classic"],
    criticScore: 93,
    grape: "Pinot Noir",
    avgPrice: 50,
    img: "https://example.com/images/veuve-clicquot-brut-yellow-label.jpg",
    linkToPurchase:
      "https://example.com/purchase/veuve-clicquot-brut-yellow-label",
  },

  {
    name: "Sassicaia",
    category: "Red",
    year: 2016,
    region: "Tuscany",
    winery: "Tenuta San Guido",
    description:
      "An elegant wine with notes of blackcurrant, cherry, and spice. Full-bodied with firm tannins.",
    tags: ["blackcurrant", "cherry", "spice", "elegant"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 300,
    img: "https://example.com/images/sassicaia.jpg",
    linkToPurchase: "https://example.com/purchase/sassicaia",
  },

  {
    name: "Screaming Eagle",
    category: "Red",
    year: 2017,
    region: "Napa Valley",
    winery: "Screaming Eagle",
    description:
      "An opulent wine with intense flavors of blackberry, cassis, and oak. Full-bodied with a velvety texture.",
    tags: ["blackberry", "cassis", "oak", "opulent"],
    criticScore: 100,
    grape: "Cabernet Sauvignon",
    avgPrice: 3000,
    img: "https://example.com/images/screaming-eagle.jpg",
    linkToPurchase: "https://example.com/purchase/screaming-eagle",
  },

  {
    name: "Cloudy Bay Te Koko",
    category: "White",
    year: 2018,
    region: "Marlborough",
    winery: "Cloudy Bay",
    description:
      "A complex and textured wine with aromas of citrus, stone fruit, and oak. Crisp acidity and long finish.",
    tags: ["citrus", "stone fruit", "oak", "textured"],
    criticScore: 94,
    grape: "Sauvignon Blanc",
    avgPrice: 40,
    img: "https://example.com/images/cloudy-bay-te-koko.jpg",
    linkToPurchase: "https://example.com/purchase/cloudy-bay-te-koko",
  },
  {
    name: "Taittinger Comtes de Champagne",
    category: "Sparkling",
    year: 2008,
    region: "Champagne",
    winery: "Taittinger",
    description:
      "A luxurious champagne with fine bubbles and notes of citrus, brioche, and hazelnut. Elegant and long finish.",
    tags: ["citrus", "brioche", "hazelnut", "elegant"],
    criticScore: 96,
    grape: "Chardonnay",
    avgPrice: 180,
    img: "https://example.com/images/taittinger-comtes-de-champagne.jpg",
    linkToPurchase:
      "https://example.com/purchase/taittinger-comtes-de-champagne",
  },

  {
    name: "Turley Zinfandel",
    category: "Red",
    year: 2018,
    region: "California",
    winery: "Turley Wine Cellars",
    description:
      "A bold and spicy wine with notes of blackberry, pepper, and licorice. Full-bodied with a long finish.",
    tags: ["blackberry", "pepper", "licorice", "bold"],
    criticScore: 92,
    grape: "Zinfandel",
    avgPrice: 50,
    img: "https://example.com/images/turley-zinfandel.jpg",
    linkToPurchase: "https://example.com/purchase/turley-zinfandel",
  },
  {
    name: "Elio Altare Barolo",
    category: "Red",
    year: 2015,
    region: "Piedmont",
    winery: "Elio Altare",
    description:
      "A complex and aromatic wine with flavors of cherry, rose, and tar. Silky tannins and long finish.",
    tags: ["cherry", "rose", "tar", "complex"],
    criticScore: 95,
    grape: "Nebbiolo",
    avgPrice: 100,
    img: "https://example.com/images/elio-altare-barolo.jpg",
    linkToPurchase: "https://example.com/purchase/elio-altare-barolo",
  },
  {
    name: "Vega Sicilia Unico",
    category: "Red",
    year: 2010,
    region: "Ribera del Duero",
    winery: "Vega Sicilia",
    description:
      "A complex and elegant wine with flavors of black cherry, tobacco, and leather. Full-bodied with a long finish.",
    tags: ["black cherry", "tobacco", "leather", "elegant"],
    criticScore: 97,
    grape: "Tempranillo",
    avgPrice: 400,
    img: "https://example.com/images/vega-sicilia-unico.jpg",
    linkToPurchase: "https://example.com/purchase/vega-sicilia-unico",
  },
  {
    name: "Kistler Chardonnay",
    category: "White",
    year: 2018,
    region: "Sonoma",
    winery: "Kistler Vineyards",
    description:
      "A rich and creamy wine with aromas of apple, pear, and oak. Full-bodied with a long finish.",
    tags: ["apple", "pear", "oak", "creamy"],
    criticScore: 95,
    grape: "Chardonnay",
    avgPrice: 80,
    img: "https://example.com/images/kistler-chardonnay.jpg",
    linkToPurchase: "https://example.com/purchase/kistler-chardonnay",
  },

  {
    name: "Krug Grande Cuvee",
    category: "Sparkling",
    year: "NV",
    region: "Champagne",
    winery: "Krug",
    description:
      "A prestigious champagne with fine bubbles and aromas of citrus, almond, and brioche. Rich and complex texture.",
    tags: ["citrus", "almond", "brioche", "complex"],
    criticScore: 97,
    grape: "Chardonnay",
    avgPrice: 200,
    img: "https://example.com/images/krug-grande-cuvee.jpg",
    linkToPurchase: "https://example.com/purchase/krug-grande-cuvee",
  },
  {
    name: "Clos Apalta",
    category: "Red",
    year: 2014,
    region: "Colchagua Valley",
    winery: "Casa Lapostolle",
    description:
      "A rich and concentrated wine with flavors of blackberry, plum, and chocolate. Full-bodied with a long finish.",
    tags: ["blackberry", "plum", "chocolate", "concentrated"],
    criticScore: 96,
    grape: "Carmenere",
    avgPrice: 120,
    img: "https://example.com/images/clos-apalta.jpg",
    linkToPurchase: "https://example.com/purchase/clos-apalta",
  },
  {
    name: "Far Niente Chardonnay",
    category: "White",
    year: 2019,
    region: "Napa Valley",
    winery: "Far Niente",
    description:
      "A balanced and elegant wine with notes of apple, pear, and vanilla. Medium-bodied with a crisp finish.",
    tags: ["apple", "pear", "vanilla", "elegant"],
    criticScore: 93,
    grape: "Chardonnay",
    avgPrice: 70,
    img: "https://example.com/images/far-niente-chardonnay.jpg",
    linkToPurchase: "https://example.com/purchase/far-niente-chardonnay",
  },
  {
    name: "Tignanello",
    category: "Red",
    year: 2016,
    region: "Tuscany",
    winery: "Antinori",
    description:
      "A complex and aromatic wine with flavors of cherry, tobacco, and spice. Full-bodied with firm tannins.",
    tags: ["cherry", "tobacco", "spice", "aromatic"],
    criticScore: 96,
    grape: "Sangiovese",
    avgPrice: 150,
    img: "https://example.com/images/tignanello.jpg",
    linkToPurchase: "https://example.com/purchase/tignanello",
  },
  {
    name: "Joseph Phelps Insignia",
    category: "Red",
    year: 2015,
    region: "Napa Valley",
    winery: "Joseph Phelps",
    description:
      "A rich and powerful wine with notes of blackberry, cassis, and oak. Full-bodied with a long finish.",
    tags: ["blackberry", "cassis", "oak", "powerful"],
    criticScore: 98,
    grape: "Cabernet Sauvignon",
    avgPrice: 250,
    img: "https://example.com/images/joseph-phelps-insignia.jpg",
    linkToPurchase: "https://example.com/purchase/joseph-phelps-insignia",
  },

  {
    name: "Chablis Grand Cru",
    category: "White",
    year: 2018,
    region: "Burgundy",
    winery: "Domaine William Fevre",
    description:
      "A crisp and mineral-driven wine with flavors of green apple, citrus, and flint. Medium-bodied with a refreshing finish.",
    tags: ["green apple", "citrus", "flint", "crisp"],
    criticScore: 94,
    grape: "Chardonnay",
    avgPrice: 100,
    img: "https://example.com/images/chablis-grand-cru.jpg",
    linkToPurchase: "https://example.com/purchase/chablis-grand-cru",
  },
  {
    name: "Louis Roederer Cristal",
    category: "Sparkling",
    year: 2012,
    region: "Champagne",
    winery: "Louis Roederer",
    description:
      "A prestigious champagne with fine bubbles and flavors of white fruit, almond, and honey. Rich and creamy texture.",
    tags: ["white fruit", "almond", "honey", "creamy"],
    criticScore: 98,
    grape: "Pinot Noir",
    avgPrice: 300,
    img: "https://example.com/images/louis-roederer-cristal.jpg",
    linkToPurchase: "https://example.com/purchase/louis-roederer-cristal",
  },
  {
    name: "Taylor Fladgate Vintage Port",
    category: "Dessert",
    year: 2011,
    region: "Douro Valley",
    winery: "Taylor Fladgate",
    description:
      "A rich and sweet wine with flavors of blackberry, plum, and chocolate. Full-bodied with a long, smooth finish.",
    tags: ["blackberry", "plum", "chocolate", "sweet"],
    criticScore: 96,
    grape: "Touriga Nacional",
    avgPrice: 120,
    img: "https://example.com/images/taylor-fladgate-vintage-port.jpg",
    linkToPurchase: "https://example.com/purchase/taylor-fladgate-vintage-port",
  },

  {
    name: "Gaja Barbaresco",
    category: "Red",
    year: 2016,
    region: "Piedmont",
    winery: "Gaja",
    description:
      "A complex and elegant wine with flavors of cherry, rose, and tar. Medium-bodied with a long finish.",
    tags: ["cherry", "rose", "tar", "elegant"],
    criticScore: 96,
    grape: "Nebbiolo",
    avgPrice: 180,
    img: "https://example.com/images/gaja-barbaresco.jpg",
    linkToPurchase: "https://example.com/purchase/gaja-barbaresco",
  },
  {
    name: "Piper-Heidsieck Brut",
    category: "Sparkling",
    year: "NV",
    region: "Champagne",
    winery: "Piper-Heidsieck",
    description:
      "A vibrant champagne with flavors of apple, citrus, and brioche. Crisp and refreshing with fine bubbles.",
    tags: ["apple", "citrus", "brioche", "vibrant"],
    criticScore: 91,
    grape: "Chardonnay",
    avgPrice: 50,
    img: "https://example.com/images/piper-heidsieck-brut.jpg",
    linkToPurchase: "https://example.com/purchase/piper-heidsieck-brut",
  },
  {
    name: "Chateau de Beaucastel Chateauneuf-du-Pape",
    category: "Red",
    year: 2017,
    region: "Rhone Valley",
    winery: "Chateau de Beaucastel",
    description:
      "A rich and spicy wine with flavors of dark berries, herbs, and pepper. Full-bodied with a long finish.",
    tags: ["dark berries", "herbs", "pepper", "spicy"],
    criticScore: 95,
    grape: "Grenache",
    avgPrice: 90,
    img: "https://example.com/images/chateau-de-beaucastel.jpg",
    linkToPurchase: "https://example.com/purchase/chateau-de-beaucastel",
  },

  {
    name: "Penfolds Grange",
    category: "Red",
    year: 2015,
    region: "South Australia",
    winery: "Penfolds",
    description:
      "A rich and opulent wine with flavors of blackberry, plum, and licorice. Full-bodied with a long, smooth finish.",
    tags: ["blackberry", "plum", "licorice", "opulent"],
    criticScore: 98,
    grape: "Shiraz",
    avgPrice: 600,
    img: "https://example.com/images/penfolds-grange.jpg",
    linkToPurchase: "https://example.com/purchase/penfolds-grange",
  },
  {
    name: "Bollinger Special Cuvée",
    category: "Sparkling",
    year: "NV",
    region: "Champagne",
    winery: "Bollinger",
    description:
      "A refined champagne with flavors of apple, pear, and toasted bread. Crisp and refreshing with fine bubbles.",
    tags: ["apple", "pear", "toasted bread", "refined"],
    criticScore: 93,
    grape: "Pinot Noir",
    avgPrice: 60,
    img: "https://example.com/images/bollinger-special-cuvee.jpg",
    linkToPurchase: "https://example.com/purchase/bollinger-special-cuvee",
  },
  {
    name: "Chateau d'Yquem",
    category: "Dessert",
    year: 2011,
    region: "Bordeaux",
    winery: "Chateau d'Yquem",
    description:
      "A luscious and sweet wine with flavors of apricot, honey, and almond. Full-bodied with a long, smooth finish.",
    tags: ["apricot", "honey", "almond", "luscious"],
    criticScore: 98,
    grape: "Sauvignon Blanc",
    avgPrice: 500,
    img: "https://example.com/images/chateau-dyquem.jpg",
    linkToPurchase: "https://example.com/purchase/chateau-dyquem",
  },
  {
    name: "Ridge Monte Bello",
    category: "Red",
    year: 2014,
    region: "California",
    winery: "Ridge Vineyards",
    description:
      "A bold and complex wine with flavors of blackberry, cassis, and oak. Full-bodied with firm tannins and a long finish.",
    tags: ["blackberry", "cassis", "oak", "bold"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 250,
    img: "https://example.com/images/ridge-monte-bello.jpg",
    linkToPurchase: "https://example.com/purchase/ridge-monte-bello",
  },
  {
    name: "Domaines Ott Château de Selle Rosé",
    category: "Rose",
    year: 2019,
    region: "Provence",
    winery: "Domaines Ott",
    description:
      "A delicate and elegant rosé with flavors of strawberry, peach, and citrus. Light-bodied with a refreshing finish.",
    tags: ["strawberry", "peach", "citrus", "delicate"],
    criticScore: 91,
    grape: "Grenache",
    avgPrice: 45,
    img: "https://example.com/images/domaines-ott-rose.jpg",
    linkToPurchase: "https://example.com/purchase/domaines-ott-rose",
  },
  {
    name: "Henschke Hill of Grace",
    category: "Red",
    year: 2013,
    region: "South Australia",
    winery: "Henschke",
    description:
      "A rich and complex wine with flavors of blackberry, plum, and spice. Full-bodied with a long, smooth finish.",
    tags: ["blackberry", "plum", "spice", "complex"],
    criticScore: 98,
    grape: "Shiraz",
    avgPrice: 700,
    img: "https://example.com/images/henschke-hill-of-grace.jpg",
    linkToPurchase: "https://example.com/purchase/henschke-hill-of-grace",
  },

  {
    name: "Chateau Montelena Chardonnay",
    category: "White",
    year: 2018,
    region: "California",
    winery: "Chateau Montelena",
    description:
      "A rich and creamy wine with flavors of apple, pear, and vanilla. Full-bodied with a long, smooth finish.",
    tags: ["apple", "pear", "vanilla", "creamy"],
    criticScore: 94,
    grape: "Chardonnay",
    avgPrice: 55,
    img: "https://example.com/images/chateau-montelena-chardonnay.jpg",
    linkToPurchase: "https://example.com/purchase/chateau-montelena-chardonnay",
  },
  {
    name: "Dom Perignon",
    category: "Sparkling",
    year: 2008,
    region: "Champagne",
    winery: "Moet & Chandon",
    description:
      "A luxurious champagne with flavors of citrus, almond, and brioche. Rich and creamy with fine bubbles.",
    tags: ["citrus", "almond", "brioche", "luxurious"],
    criticScore: 97,
    grape: "Chardonnay",
    avgPrice: 180,
    img: "https://example.com/images/dom-perignon.jpg",
    linkToPurchase: "https://example.com/purchase/dom-perignon",
  },
  {
    name: "Chateau Ste. Michelle Riesling",
    category: "White",
    year: 2019,
    region: "Washington",
    winery: "Chateau Ste. Michelle",
    description:
      "A crisp and refreshing wine with flavors of green apple, citrus, and peach. Light-bodied with a clean finish.",
    tags: ["green apple", "citrus", "peach", "crisp"],
    criticScore: 90,
    grape: "Riesling",
    avgPrice: 12,
    img: "https://example.com/images/chateau-ste-michelle-riesling.jpg",
    linkToPurchase:
      "https://example.com/purchase/chateau-ste-michelle-riesling",
  },
  {
    name: "Château Cheval Blanc",
    category: "Red",
    year: 2010,
    region: "Bordeaux",
    winery: "Château Cheval Blanc",
    description:
      "A refined and aromatic wine with notes of blackberry, plum, and truffle. Medium-bodied with a silky texture.",
    tags: ["blackberry", "plum", "truffle", "refined"],
    criticScore: 98,
    grape: "Merlot",
    avgPrice: 450,
    img: "https://example.com/images/chevalblanc.jpg",
    linkToPurchase: "https://example.com/purchase/chevalblanc",
  },
  {
    name: "Château d'Yquem",
    category: "Dessert",
    year: 2005,
    region: "Sauternes",
    winery: "Château d'Yquem",
    description:
      "A luxurious and sweet wine with flavors of apricot, honey, and vanilla. Rich and full-bodied.",
    tags: ["apricot", "honey", "vanilla", "luxurious"],
    criticScore: 99,
    grape: "Sauvignon Blanc",
    avgPrice: 350,
    img: "https://example.com/images/dyquem.jpg",
    linkToPurchase: "https://example.com/purchase/dyquem",
  },
  {
    name: "Roederer Estate L'Ermitage",
    category: "Sparkling",
    year: 2012,
    region: "California",
    winery: "Roederer Estate",
    description:
      "A crisp and refreshing sparkling wine with notes of apple, pear, and brioche. Well-balanced with fine bubbles.",
    tags: ["apple", "pear", "brioche", "crisp"],
    criticScore: 93,
    grape: "Chardonnay",
    avgPrice: 70,
    img: "https://example.com/images/lermitage.jpg",
    linkToPurchase: "https://example.com/purchase/lermitage",
  },
  {
    name: "Château Palmer",
    category: "Red",
    year: 2015,
    region: "Margaux",
    winery: "Château Palmer",
    description:
      "An elegant and structured wine with flavors of dark fruit, spices, and cedar. Full-bodied with a long finish.",
    tags: ["dark fruit", "spices", "cedar", "elegant"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 300,
    img: "https://example.com/images/chateaupalmer.jpg",
    linkToPurchase: "https://example.com/purchase/chateaupalmer",
  },

  {
    name: "Penfolds Bin 389",
    category: "Red",
    year: 2016,
    region: "South Australia",
    winery: "Penfolds",
    description:
      "A rich and balanced wine with flavors of dark chocolate, blackcurrant, and oak. Medium-bodied with smooth tannins.",
    tags: ["dark chocolate", "blackcurrant", "oak", "rich"],
    criticScore: 94,
    grape: "Shiraz",
    avgPrice: 80,
    img: "https://example.com/images/bin389.jpg",
    linkToPurchase: "https://example.com/purchase/bin389",
  },
  {
    name: "Bollinger La Grande Année",
    category: "Sparkling",
    year: 2008,
    region: "Champagne",
    winery: "Bollinger",
    description:
      "A sophisticated and elegant sparkling wine with notes of apple, citrus, and toast. Fine bubbles and a long finish.",
    tags: ["apple", "citrus", "toast", "sophisticated"],
    criticScore: 97,
    grape: "Pinot Noir",
    avgPrice: 150,
    img: "https://example.com/images/lagrandeannee.jpg",
    linkToPurchase: "https://example.com/purchase/lagrandeannee",
  },
  {
    name: "Château Pichon Longueville",
    category: "Red",
    year: 2012,
    region: "Pauillac",
    winery: "Château Pichon Longueville",
    description:
      "A bold and complex wine with flavors of cassis, tobacco, and leather. Full-bodied with a long, structured finish.",
    tags: ["cassis", "tobacco", "leather", "bold"],
    criticScore: 95,
    grape: "Cabernet Sauvignon",
    avgPrice: 180,
    img: "https://example.com/images/pichonlongueville.jpg",
    linkToPurchase: "https://example.com/purchase/pichonlongueville",
  },
  {
    name: "Heitz Cellar Martha's Vineyard",
    category: "Red",
    year: 2013,
    region: "Napa Valley",
    winery: "Heitz Cellar",
    description:
      "A classic and balanced wine with flavors of mint, blackberry, and vanilla. Full-bodied with a smooth finish.",
    tags: ["mint", "blackberry", "vanilla", "classic"],
    criticScore: 94,
    grape: "Cabernet Sauvignon",
    avgPrice: 200,
    img: "https://example.com/images/marthasvineyard.jpg",
    linkToPurchase: "https://example.com/purchase/marthasvineyard",
  },
  {
    name: "Domaine de la Romanée-Conti",
    category: "Red",
    year: 2011,
    region: "Burgundy",
    winery: "Domaine de la Romanée-Conti",
    description:
      "A legendary and rare wine with flavors of cherry, earth, and spice. Medium-bodied with an exceptional finish.",
    tags: ["cherry", "earth", "spice", "legendary"],
    criticScore: 99,
    grape: "Pinot Noir",
    avgPrice: 14000,
    img: "https://example.com/images/romaneeconti.jpg",
    linkToPurchase: "https://example.com/purchase/romaneeconti",
  },
  {
    name: "Château Margaux",
    category: "Red",
    year: 2010,
    region: "Bordeaux",
    winery: "Château Margaux",
    description:
      "A sublime and aromatic wine with flavors of black cherry, plum, and violet. Full-bodied with a velvety texture.",
    tags: ["black cherry", "plum", "violet", "sublime"],
    criticScore: 98,
    grape: "Cabernet Sauvignon",
    avgPrice: 700,
    img: "https://example.com/images/chateaumargaux.jpg",
    linkToPurchase: "https://example.com/purchase/chateaumargaux",
  },
  {
    name: "Joseph Phelps Insignia",
    category: "Red",
    year: 2014,
    region: "Napa Valley",
    winery: "Joseph Phelps",
    description:
      "A rich and complex wine with notes of blackberry, mocha, and graphite. Full-bodied with a smooth finish.",
    tags: ["blackberry", "mocha", "graphite", "rich"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 250,
    img: "https://example.com/images/insignia.jpg",
    linkToPurchase: "https://example.com/purchase/insignia",
  },

  {
    name: "Tignanello",
    category: "Red",
    year: 2013,
    region: "Tuscany",
    winery: "Antinori",
    description:
      "A bold and structured wine with flavors of dark fruit, leather, and spice. Full-bodied with a long finish.",
    tags: ["dark fruit", "leather", "spice", "bold"],
    criticScore: 95,
    grape: "Sangiovese",
    avgPrice: 130,
    img: "https://example.com/images/tignanello.jpg",
    linkToPurchase: "https://example.com/purchase/tignanello",
  },

  {
    name: "Louis Roederer Cristal",
    category: "Sparkling",
    year: 2009,
    region: "Champagne",
    winery: "Louis Roederer",
    description:
      "A luxurious and elegant champagne with flavors of citrus, apricot, and brioche. Fine bubbles and a long finish.",
    tags: ["citrus", "apricot", "brioche", "luxurious"],
    criticScore: 98,
    grape: "Chardonnay",
    avgPrice: 250,
    img: "https://example.com/images/cristal.jpg",
    linkToPurchase: "https://example.com/purchase/cristal",
  },
  {
    name: "Château Rieussec",
    category: "Dessert",
    year: 2011,
    region: "Sauternes",
    winery: "Château Rieussec",
    description:
      "A sweet and luscious wine with flavors of honey, apricot, and vanilla. Rich and full-bodied with a long finish.",
    tags: ["honey", "apricot", "vanilla", "luscious"],
    criticScore: 95,
    grape: "Sémillon",
    avgPrice: 70,
    img: "https://example.com/images/rieussec.jpg",
    linkToPurchase: "https://example.com/purchase/rieussec",
  },
  {
    name: "Château Lynch-Bages",
    category: "Red",
    year: 2010,
    region: "Pauillac",
    winery: "Château Lynch-Bages",
    description:
      "A powerful and structured wine with flavors of cassis, tobacco, and leather. Full-bodied with firm tannins.",
    tags: ["cassis", "tobacco", "leather", "powerful"],
    criticScore: 96,
    grape: "Cabernet Sauvignon",
    avgPrice: 170,
    img: "https://example.com/images/lynchbages.jpg",
    linkToPurchase: "https://example.com/purchase/lynchbages",
  },

  {
    name: "Penfolds Yattarna Chardonnay",
    category: "White",
    year: 2017,
    region: "South Australia",
    winery: "Penfolds",
    description:
      "A refined and complex wine with flavors of citrus, peach, and oak. Medium-bodied with a creamy texture.",
    tags: ["citrus", "peach", "oak", "refined"],
    criticScore: 94,
    grape: "Chardonnay",
    avgPrice: 120,
    img: "https://example.com/images/yattarna.jpg",
    linkToPurchase: "https://example.com/purchase/yattarna",
  },
  {
    name: "Opus One",
    category: "Red",
    year: 2015,
    region: "Napa Valley",
    winery: "Opus One Winery",
    description:
      "A harmonious and balanced wine with flavors of blackberry, cassis, and mocha. Full-bodied with a long, elegant finish.",
    tags: ["blackberry", "cassis", "mocha", "harmonious"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 350,
    img: "https://example.com/images/opusone.jpg",
    linkToPurchase: "https://example.com/purchase/opusone",
  },
  {
    name: "Château Montrose",
    category: "Red",
    year: 2012,
    region: "Saint-Estèphe",
    winery: "Château Montrose",
    description:
      "A powerful and structured wine with flavors of blackcurrant, cedar, and graphite. Full-bodied with firm tannins.",
    tags: ["blackcurrant", "cedar", "graphite", "powerful"],
    criticScore: 96,
    grape: "Cabernet Sauvignon",
    avgPrice: 200,
    img: "https://example.com/images/chateaumontrose.jpg",
    linkToPurchase: "https://example.com/purchase/chateaumontrose",
  },

  {
    name: "Egon Müller Scharzhofberger Riesling",
    category: "White",
    year: 2016,
    region: "Mosel",
    winery: "Weingut Egon Müller",
    description:
      "A vibrant and aromatic wine with flavors of peach, apricot, and slate. Light-bodied with a racy acidity.",
    tags: ["peach", "apricot", "slate", "vibrant"],
    criticScore: 97,
    grape: "Riesling",
    avgPrice: 120,
    img: "https://example.com/images/egonmuller.jpg",
    linkToPurchase: "https://example.com/purchase/egonmuller",
  },
  {
    name: "Dom Pérignon",
    category: "Sparkling",
    year: 2008,
    region: "Champagne",
    winery: "Moët & Chandon",
    description:
      "A luxurious and elegant champagne with flavors of citrus, almond, and brioche. Fine bubbles and a long, creamy finish.",
    tags: ["citrus", "almond", "brioche", "luxurious"],
    criticScore: 98,
    grape: "Chardonnay",
    avgPrice: 200,
    img: "https://example.com/images/domperignon.jpg",
    linkToPurchase: "https://example.com/purchase/domperignon",
  },
  {
    name: "Quinta do Noval Vintage Port",
    category: "Dessert",
    year: 2011,
    region: "Douro",
    winery: "Quinta do Noval",
    description:
      "A rich and opulent port with flavors of blackberry, fig, and dark chocolate. Full-bodied with a long, velvety finish.",
    tags: ["blackberry", "fig", "dark chocolate", "opulent"],
    criticScore: 97,
    grape: "Touriga Nacional",
    avgPrice: 110,
    img: "https://example.com/images/novalvintageport.jpg",
    linkToPurchase: "https://example.com/purchase/novalvintageport",
  },
  {
    name: "Château Palmer",
    category: "Red",
    year: 2016,
    region: "Margaux",
    winery: "Château Palmer",
    description:
      "An elegant and refined wine with flavors of black cherry, plum, and violet. Medium-bodied with silky tannins.",
    tags: ["black cherry", "plum", "violet", "elegant"],
    criticScore: 98,
    grape: "Merlot",
    avgPrice: 300,
    img: "https://example.com/images/chateaupalmer.jpg",
    linkToPurchase: "https://example.com/purchase/chateaupalmer",
  },
  {
    name: "Château de Beaucastel Châteauneuf-du-Pape",
    category: "Red",
    year: 2015,
    region: "Rhône",
    winery: "Château de Beaucastel",
    description:
      "A complex and spicy wine with flavors of raspberry, black pepper, and herbs. Full-bodied with a long finish.",
    tags: ["raspberry", "black pepper", "herbs", "complex"],
    criticScore: 95,
    grape: "Grenache",
    avgPrice: 100,
    img: "https://example.com/images/beaucastel.jpg",
    linkToPurchase: "https://example.com/purchase/beaucastel",
  },
  {
    name: "Château Climens",
    category: "Dessert",
    year: 2013,
    region: "Barsac",
    winery: "Château Climens",
    description:
      "A luscious and sweet wine with flavors of honey, apricot, and vanilla. Full-bodied with a long, rich finish.",
    tags: ["honey", "apricot", "vanilla", "luscious"],
    criticScore: 96,
    grape: "Sémillon",
    avgPrice: 90,
    img: "https://example.com/images/climens.jpg",
    linkToPurchase: "https://example.com/purchase/climens",
  },
  {
    name: "Louis Latour Corton-Charlemagne",
    category: "White",
    year: 2014,
    region: "Burgundy",
    winery: "Louis Latour",
    description:
      "A rich and creamy wine with flavors of peach, hazelnut, and butter. Full-bodied with a long, smooth finish.",
    tags: ["peach", "hazelnut", "butter", "rich"],
    criticScore: 94,
    grape: "Chardonnay",
    avgPrice: 150,
    img: "https://example.com/images/cortoncharlemagne.jpg",
    linkToPurchase: "https://example.com/purchase/cortoncharlemagne",
  },
  {
    name: "Armand de Brignac Ace of Spades",
    category: "Sparkling",
    year: 2010,
    region: "Champagne",
    winery: "Armand de Brignac",
    description:
      "A prestigious and opulent champagne with flavors of apricot, peach, and brioche. Fine bubbles with a luxurious finish.",
    tags: ["apricot", "peach", "brioche", "opulent"],
    criticScore: 98,
    grape: "Pinot Noir",
    avgPrice: 300,
    img: "https://example.com/images/aceofspades.jpg",
    linkToPurchase: "https://example.com/purchase/aceofspades",
  },
  {
    name: "Almaviva",
    category: "Red",
    year: 2017,
    region: "Puente Alto",
    winery: "Almaviva",
    description:
      "A refined and balanced wine with flavors of black cherry, cassis, and espresso. Full-bodied with velvety tannins.",
    tags: ["black cherry", "cassis", "espresso", "refined"],
    criticScore: 95,
    grape: "Cabernet Sauvignon",
    avgPrice: 150,
    img: "https://example.com/images/almaviva.jpg",
    linkToPurchase: "https://example.com/purchase/almaviva",
  },
  {
    name: "Almaviva",
    category: "Red",
    year: 2016,
    region: "Maipo Valley",
    winery: "Almaviva",
    description:
      "A bold and elegant wine with flavors of blackberry, cassis, and spice. Full-bodied with a long, smooth finish.",
    tags: ["blackberry", "cassis", "spice", "bold"],
    criticScore: 95,
    grape: "Cabernet Sauvignon",
    avgPrice: 150,
    img: "https://example.com/images/almaviva.jpg",
    linkToPurchase: "https://example.com/purchase/almaviva",
  },
  {
    name: "Marchesi Antinori Tignanello",
    category: "Red",
    year: 2016,
    region: "Tuscany",
    winery: "Marchesi Antinori",
    description:
      "A complex and structured wine with flavors of red cherry, plum, and tobacco. Full-bodied with a long finish.",
    tags: ["red cherry", "plum", "tobacco", "complex"],
    criticScore: 96,
    grape: "Sangiovese",
    avgPrice: 135,
    img: "https://example.com/images/tignanello.jpg",
    linkToPurchase: "https://example.com/purchase/tignanello",
  },
  {
    name: "Penfolds Bin 707",
    category: "Red",
    year: 2015,
    region: "Barossa Valley",
    winery: "Penfolds",
    description:
      "A rich and intense wine with flavors of blackcurrant, dark chocolate, and mint. Full-bodied with firm tannins.",
    tags: ["blackcurrant", "dark chocolate", "mint", "intense"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 250,
    img: "https://example.com/images/bin707.jpg",
    linkToPurchase: "https://example.com/purchase/bin707",
  },
  {
    name: "Sine Qua Non Syrah",
    category: "Red",
    year: 2013,
    region: "California",
    winery: "Sine Qua Non",
    description:
      "A bold and powerful wine with flavors of blackberry, olive, and pepper. Full-bodied with a long, spicy finish.",
    tags: ["blackberry", "olive", "pepper", "bold"],
    criticScore: 98,
    grape: "Syrah",
    avgPrice: 250,
    img: "https://example.com/images/syrah.jpg",
    linkToPurchase: "https://example.com/purchase/syrah",
  },
  {
    name: "Domaine de la Romanée-Conti Montrachet",
    category: "White",
    year: 2014,
    region: "Burgundy",
    winery: "Domaine de la Romanée-Conti",
    description:
      "A rare and exquisite wine with flavors of white peach, hazelnut, and honey. Full-bodied with a long, mineral finish.",
    tags: ["white peach", "hazelnut", "honey", "exquisite"],
    criticScore: 99,
    grape: "Chardonnay",
    avgPrice: 3500,
    img: "https://example.com/images/montrachet.jpg",
    linkToPurchase: "https://example.com/purchase/montrachet",
  },
  {
    name: "Bodegas Vega Sicilia Unico",
    category: "Red",
    year: 2009,
    region: "Ribera del Duero",
    winery: "Bodegas Vega Sicilia",
    description:
      "A legendary and complex wine with flavors of black cherry, leather, and truffle. Full-bodied with a long, elegant finish.",
    tags: ["black cherry", "leather", "truffle", "legendary"],
    criticScore: 97,
    grape: "Tempranillo",
    avgPrice: 300,
    img: "https://example.com/images/vega-sicilia.jpg",
    linkToPurchase: "https://example.com/purchase/vega-sicilia",
  },
  {
    name: "Joseph Phelps Insignia",
    category: "Red",
    year: 2016,
    region: "Napa Valley",
    winery: "Joseph Phelps Vineyards",
    description:
      "A rich and layered wine with flavors of blackberry, mocha, and anise. Full-bodied with a long, complex finish.",
    tags: ["blackberry", "mocha", "anise", "layered"],
    criticScore: 98,
    grape: "Cabernet Sauvignon",
    avgPrice: 250,
    img: "https://example.com/images/insignia.jpg",
    linkToPurchase: "https://example.com/purchase/insignia",
  },

  {
    name: "Gaja Barbaresco",
    category: "Red",
    year: 2015,
    region: "Piedmont",
    winery: "Gaja",
    description:
      "A refined and elegant wine with flavors of cherry, rose petal, and licorice. Medium-bodied with fine tannins.",
    tags: ["cherry", "rose petal", "licorice", "elegant"],
    criticScore: 96,
    grape: "Nebbiolo",
    avgPrice: 200,
    img: "https://example.com/images/gaja-barbaresco.jpg",
    linkToPurchase: "https://example.com/purchase/gaja-barbaresco",
  },
  {
    name: "Opus One",
    category: "Red",
    year: 2016,
    region: "Napa Valley",
    winery: "Opus One Winery",
    description:
      "A rich and elegant wine with flavors of blackberry, cassis, and dark chocolate. Full-bodied with a silky finish.",
    tags: ["blackberry", "cassis", "dark chocolate", "elegant"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 300,
    img: "https://example.com/images/opusone.jpg",
    linkToPurchase: "https://example.com/purchase/opusone",
  },

  {
    name: "Roederer Estate L'Ermitage Brut",
    category: "Sparkling",
    year: 2012,
    region: "Anderson Valley",
    winery: "Roederer Estate",
    description:
      "A sophisticated and balanced sparkling wine with flavors of pear, almond, and brioche. Fine bubbles with a long, elegant finish.",
    tags: ["pear", "almond", "brioche", "sophisticated"],
    criticScore: 94,
    grape: "Chardonnay",
    avgPrice: 60,
    img: "https://example.com/images/lermitagebrut.jpg",
    linkToPurchase: "https://example.com/purchase/lermitagebrut",
  },

  {
    name: "Caymus Special Selection",
    category: "Red",
    year: 2017,
    region: "Napa Valley",
    winery: "Caymus Vineyards",
    description:
      "A bold and rich wine with flavors of blackberry, cocoa, and vanilla. Full-bodied with velvety tannins and a long finish.",
    tags: ["blackberry", "cocoa", "vanilla", "bold"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 180,
    img: "https://example.com/images/caymusspecialselection.jpg",
    linkToPurchase: "https://example.com/purchase/caymusspecialselection",
  },
  {
    name: "Rombauer Chardonnay",
    category: "White",
    year: 2019,
    region: "Carneros",
    winery: "Rombauer Vineyards",
    description:
      "A creamy and buttery wine with flavors of peach, vanilla, and oak. Full-bodied with a smooth, rich finish.",
    tags: ["peach", "vanilla", "oak", "creamy"],
    criticScore: 92,
    grape: "Chardonnay",
    avgPrice: 40,
    img: "https://example.com/images/rombauerchardonnay.jpg",
    linkToPurchase: "https://example.com/purchase/rombauerchardonnay",
  },
  {
    name: "Chateau Montelena Cabernet Sauvignon",
    category: "Red",
    year: 2016,
    region: "Napa Valley",
    winery: "Chateau Montelena",
    description:
      "A structured and balanced wine with flavors of blackcurrant, cedar, and leather. Full-bodied with a long, firm finish.",
    tags: ["blackcurrant", "cedar", "leather", "structured"],
    criticScore: 96,
    grape: "Cabernet Sauvignon",
    avgPrice: 125,
    img: "https://example.com/images/chateaumontelena.jpg",
    linkToPurchase: "https://example.com/purchase/chateaumontelena",
  },
  {
    name: "Domaines Ott Chateau de Selle",
    category: "Rose",
    year: 2020,
    region: "Provence",
    winery: "Domaines Ott",
    description:
      "A fresh and aromatic wine with flavors of strawberry, peach, and rose petal. Light-bodied with a crisp, clean finish.",
    tags: ["strawberry", "peach", "rose petal", "fresh"],
    criticScore: 93,
    grape: "Grenache",
    avgPrice: 55,
    img: "https://example.com/images/chateaudeselle.jpg",
    linkToPurchase: "https://example.com/purchase/chateaudeselle",
  },
  {
    name: "Pio Cesare Barolo",
    category: "Red",
    year: 2015,
    region: "Piedmont",
    winery: "Pio Cesare",
    description:
      "A powerful and elegant wine with flavors of cherry, rose, and tar. Full-bodied with firm tannins and a long finish.",
    tags: ["cherry", "rose", "tar", "elegant"],
    criticScore: 95,
    grape: "Nebbiolo",
    avgPrice: 85,
    img: "https://example.com/images/piocesarebarolo.jpg",
    linkToPurchase: "https://example.com/purchase/piocesarebarolo",
  },
  {
    name: "Veuve Clicquot La Grande Dame",
    category: "Sparkling",
    year: 2012,
    region: "Champagne",
    winery: "Veuve Clicquot",
    description:
      "A refined and complex Champagne with flavors of apple, pear, and brioche. Elegant with a long, creamy finish.",
    tags: ["apple", "pear", "brioche", "refined"],
    criticScore: 96,
    grape: "Chardonnay",
    avgPrice: 150,
    img: "https://example.com/images/lagrandedame.jpg",
    linkToPurchase: "https://example.com/purchase/lagrandedame",
  },
  {
    name: "Louis Roederer Cristal",
    category: "Sparkling",
    year: 2013,
    region: "Champagne",
    winery: "Louis Roederer",
    description:
      "A luxurious and elegant Champagne with flavors of white fruit, citrus, and honey. Fine bubbles with a long, silky finish.",
    tags: ["white fruit", "citrus", "honey", "luxurious"],
    criticScore: 97,
    grape: "Pinot Noir",
    avgPrice: 300,
    img: "https://example.com/images/cristal.jpg",
    linkToPurchase: "https://example.com/purchase/cristal",
  },
  {
    name: "Beringer Private Reserve Cabernet Sauvignon",
    category: "Red",
    year: 2017,
    region: "Napa Valley",
    winery: "Beringer Vineyards",
    description:
      "A rich and powerful wine with flavors of black cherry, mocha, and vanilla. Full-bodied with a long, velvety finish.",
    tags: ["black cherry", "mocha", "vanilla", "rich"],
    criticScore: 95,
    grape: "Cabernet Sauvignon",
    avgPrice: 150,
    img: "https://example.com/images/beringer.jpg",
    linkToPurchase: "https://example.com/purchase/beringer",
  },
  {
    name: "Cloudy Bay Sauvignon Blanc",
    category: "White",
    year: 2019,
    region: "Marlborough",
    winery: "Cloudy Bay",
    description:
      "A vibrant and aromatic wine with flavors of lime, passion fruit, and green pepper. Crisp and refreshing finish.",
    tags: ["lime", "passion fruit", "green pepper", "vibrant"],
    criticScore: 92,
    grape: "Sauvignon Blanc",
    avgPrice: 30,
    img: "https://example.com/images/cloudybay.jpg",
    linkToPurchase: "https://example.com/purchase/cloudybay",
  },
  {
    name: "Chateau Ste. Michelle Riesling",
    category: "White",
    year: 2018,
    region: "Columbia Valley",
    winery: "Chateau Ste. Michelle",
    description:
      "A crisp and off-dry wine with flavors of peach, apricot, and citrus. Medium-bodied with a clean, refreshing finish.",
    tags: ["peach", "apricot", "citrus", "crisp"],
    criticScore: 91,
    grape: "Riesling",
    avgPrice: 15,
    img: "https://example.com/images/chateaustemichelle.jpg",
    linkToPurchase: "https://example.com/purchase/chateaustemichelle",
  },

  {
    name: "Chateau Lynch-Bages",
    category: "Red",
    year: 2015,
    region: "Bordeaux",
    winery: "Chateau Lynch-Bages",
    description:
      "A bold and structured wine with flavors of blackcurrant, cedar, and tobacco. Full-bodied with a long, firm finish.",
    tags: ["blackcurrant", "cedar", "tobacco", "bold"],
    criticScore: 95,
    grape: "Cabernet Sauvignon",
    avgPrice: 120,
    img: "https://example.com/images/lynchbages.jpg",
    linkToPurchase: "https://example.com/purchase/lynchbages",
  },
  {
    name: "Penfolds Bin 389 Cabernet Shiraz",
    category: "Red",
    year: 2018,
    region: "South Australia",
    winery: "Penfolds",
    description:
      "A rich and balanced wine with flavors of blackberry, plum, and spice. Full-bodied with a smooth, long finish.",
    tags: ["blackberry", "plum", "spice", "balanced"],
    criticScore: 94,
    grape: "Cabernet Sauvignon",
    avgPrice: 70,
    img: "https://example.com/images/bin389.jpg",
    linkToPurchase: "https://example.com/purchase/bin389",
  },
  {
    name: "Domaine de la Romanee-Conti La Tache",
    category: "Red",
    year: 2015,
    region: "Burgundy",
    winery: "Domaine de la Romanee-Conti",
    description:
      "A highly complex and refined wine with flavors of red fruit, spice, and earth. Full-bodied with a long, silky finish.",
    tags: ["red fruit", "spice", "earth", "refined"],
    criticScore: 98,
    grape: "Pinot Noir",
    avgPrice: 2000,
    img: "https://example.com/images/latache.jpg",
    linkToPurchase: "https://example.com/purchase/latache",
  },
  {
    name: "Chateau Haut-Brion Blanc",
    category: "White",
    year: 2016,
    region: "Bordeaux",
    winery: "Chateau Haut-Brion",
    description:
      "A luxurious and full-bodied wine with flavors of lemon, apple, and hazelnut. Long, rich finish with great complexity.",
    tags: ["lemon", "apple", "hazelnut", "luxurious"],
    criticScore: 97,
    grape: "Sauvignon Blanc",
    avgPrice: 850,
    img: "https://example.com/images/hautbrionblanc.jpg",
    linkToPurchase: "https://example.com/purchase/hautbrionblanc",
  },

  {
    name: "Solaia",
    category: "Red",
    year: 2016,
    region: "Tuscany",
    winery: "Antinori",
    description:
      "A powerful and elegant wine with flavors of blackberry, chocolate, and spice. Full-bodied with a long, smooth finish.",
    tags: ["blackberry", "chocolate", "spice", "elegant"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 350,
    img: "https://example.com/images/solaia.jpg",
    linkToPurchase: "https://example.com/purchase/solaia",
  },
  {
    name: "Clos des Papes Chateauneuf-du-Pape",
    category: "Red",
    year: 2017,
    region: "Rhone",
    winery: "Clos des Papes",
    description:
      "A rich and intense wine with flavors of red berries, licorice, and herbs. Full-bodied with a long, spicy finish.",
    tags: ["red berries", "licorice", "herbs", "intense"],
    criticScore: 96,
    grape: "Grenache",
    avgPrice: 100,
    img: "https://example.com/images/closdespapes.jpg",
    linkToPurchase: "https://example.com/purchase/closdespapes",
  },
  {
    name: "Ornellaia",
    category: "Red",
    year: 2015,
    region: "Tuscany",
    winery: "Tenuta dell'Ornellaia",
    description:
      "A refined and complex wine with flavors of black cherry, tobacco, and cedar. Full-bodied with a long, smooth finish.",
    tags: ["black cherry", "tobacco", "cedar", "refined"],
    criticScore: 98,
    grape: "Cabernet Sauvignon",
    avgPrice: 200,
    img: "https://example.com/images/ornellaia.jpg",
    linkToPurchase: "https://example.com/purchase/ornellaia",
  },
  {
    name: "Vega Sicilia Unico",
    category: "Red",
    year: 2009,
    region: "Ribera del Duero",
    winery: "Vega Sicilia",
    description:
      "A legendary and powerful wine with flavors of black fruit, leather, and spice. Full-bodied with a long, complex finish.",
    tags: ["black fruit", "leather", "spice", "legendary"],
    criticScore: 97,
    grape: "Tempranillo",
    avgPrice: 350,
    img: "https://example.com/images/vegasicilia.jpg",
    linkToPurchase: "https://example.com/purchase/vegasicilia",
  },
  {
    name: "Catena Zapata Adrianna Vineyard White Bones",
    category: "White",
    year: 2018,
    region: "Mendoza",
    winery: "Catena Zapata",
    description:
      "A unique and mineral-driven wine with flavors of citrus, white flowers, and stone. Crisp and refreshing finish.",
    tags: ["citrus", "white flowers", "stone", "mineral-driven"],
    criticScore: 95,
    grape: "Chardonnay",
    avgPrice: 150,
    img: "https://example.com/images/catenazapata.jpg",
    linkToPurchase: "https://example.com/purchase/catenazapata",
  },

  {
    name: "Bollinger La Grande Annee",
    category: "Sparkling",
    year: 2012,
    region: "Champagne",
    winery: "Bollinger",
    description:
      "A complex and refined Champagne with flavors of apple, pear, and brioche. Elegant with a long, creamy finish.",
    tags: ["apple", "pear", "brioche", "refined"],
    criticScore: 96,
    grape: "Pinot Noir",
    avgPrice: 150,
    img: "https://example.com/images/lagrandeannee.jpg",
    linkToPurchase: "https://example.com/purchase/lagrandeannee",
  },
  {
    name: "Silver Oak Napa Valley Cabernet Sauvignon",
    category: "Red",
    year: 2016,
    region: "Napa Valley",
    winery: "Silver Oak",
    description:
      "A rich and smooth wine with flavors of blackberry, vanilla, and spice. Full-bodied with a long, velvety finish.",
    tags: ["blackberry", "vanilla", "spice", "smooth"],
    criticScore: 94,
    grape: "Cabernet Sauvignon",
    avgPrice: 125,
    img: "https://example.com/images/silveroak.jpg",
    linkToPurchase: "https://example.com/purchase/silveroak",
  },
  {
    name: "Cloudy Bay Pinot Noir",
    category: "Red",
    year: 2017,
    region: "Marlborough",
    winery: "Cloudy Bay",
    description:
      "A vibrant and aromatic wine with flavors of cherry, plum, and spice. Medium-bodied with a smooth, elegant finish.",
    tags: ["cherry", "plum", "spice", "vibrant"],
    criticScore: 93,
    grape: "Pinot Noir",
    avgPrice: 45,
    img: "https://example.com/images/cloudybaypinot.jpg",
    linkToPurchase: "https://example.com/purchase/cloudybaypinot",
  },
  {
    name: "Chateau Montelena Chardonnay",
    category: "White",
    year: 2017,
    region: "Napa Valley",
    winery: "Chateau Montelena",
    description:
      "A rich and balanced wine with flavors of apple, pear, and a hint of oak. Crisp and refreshing finish.",
    tags: ["apple", "pear", "oak", "balanced"],
    criticScore: 95,
    grape: "Chardonnay",
    avgPrice: 60,
    img: "https://example.com/images/chateaumontelena.jpg",
    linkToPurchase: "https://example.com/purchase/chateaumontelena",
  },

  {
    name: "Chateau Haut-Brion",
    category: "Red",
    year: 2015,
    region: "Bordeaux",
    winery: "Chateau Haut-Brion",
    description:
      "A prestigious and refined wine with flavors of blackcurrant, tobacco, and cedar. Full-bodied with a long, graceful finish.",
    tags: ["blackcurrant", "tobacco", "cedar", "prestigious"],
    criticScore: 98,
    grape: "Merlot",
    avgPrice: 500,
    img: "https://example.com/images/hautbrion.jpg",
    linkToPurchase: "https://example.com/purchase/hautbrion",
  },
  {
    name: "Marchesi Antinori Castello della Sala Cervaro",
    category: "White",
    year: 2018,
    region: "Umbria",
    winery: "Marchesi Antinori",
    description:
      "A fresh and aromatic wine with flavors of pear, apple, and a hint of vanilla. Crisp and refreshing finish.",
    tags: ["pear", "apple", "vanilla", "aromatic"],
    criticScore: 94,
    grape: "Chardonnay",
    avgPrice: 55,
    img: "https://example.com/images/castellodellasala.jpg",
    linkToPurchase: "https://example.com/purchase/castellodellasala",
  },
  {
    name: "Opus One",
    category: "Red",
    year: 2014,
    region: "Napa Valley",
    winery: "Opus One",
    description:
      "A rich and complex wine with flavors of blackberry, plum, and spice. Full-bodied with a long, velvety finish.",
    tags: ["blackberry", "plum", "spice", "complex"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 350,
    img: "https://example.com/images/opusone.jpg",
    linkToPurchase: "https://example.com/purchase/opusone",
  },
  {
    name: "Egon Muller Scharzhofberger Riesling",
    category: "White",
    year: 2017,
    region: "Mosel",
    winery: "Egon Muller",
    description:
      "A delicate and aromatic wine with flavors of peach, apricot, and mineral notes. Crisp and refreshing finish.",
    tags: ["peach", "apricot", "mineral", "delicate"],
    criticScore: 98,
    grape: "Riesling",
    avgPrice: 200,
    img: "https://example.com/images/egonmuller.jpg",
    linkToPurchase: "https://example.com/purchase/egonmuller",
  },
  {
    name: "Masseto",
    category: "Red",
    year: 2016,
    region: "Tuscany",
    winery: "Masseto",
    description:
      "A powerful and elegant wine with flavors of black cherry, chocolate, and spice. Full-bodied with a long, smooth finish.",
    tags: ["black cherry", "chocolate", "spice", "elegant"],
    criticScore: 98,
    grape: "Merlot",
    avgPrice: 800,
    img: "https://example.com/images/masseto.jpg",
    linkToPurchase: "https://example.com/purchase/masseto",
  },
  {
    name: "Dom Perignon",
    category: "Sparkling",
    year: 2010,
    region: "Champagne",
    winery: "Moet & Chandon",
    description:
      "A luxurious and refined Champagne with flavors of citrus, almond, and brioche. Elegant with a long, creamy finish.",
    tags: ["citrus", "almond", "brioche", "refined"],
    criticScore: 96,
    grape: "Chardonnay",
    avgPrice: 200,
    img: "https://example.com/images/domperignon.jpg",
    linkToPurchase: "https://example.com/purchase/domperignon",
  },

  {
    name: "Chateau d'Yquem",
    category: "Dessert",
    year: 2009,
    region: "Sauternes",
    winery: "Chateau d'Yquem",
    description:
      "A luxurious and sweet wine with flavors of apricot, honey, and vanilla. Full-bodied with a rich, lingering finish.",
    tags: ["apricot", "honey", "vanilla", "luxurious"],
    criticScore: 98,
    grape: "Semillon",
    avgPrice: 500,
    img: "https://example.com/images/chateaudyquem.jpg",
    linkToPurchase: "https://example.com/purchase/chateaudyquem",
  },
  {
    name: "Perrier-Jouet Belle Epoque",
    category: "Sparkling",
    year: 2012,
    region: "Champagne",
    winery: "Perrier-Jouet",
    description:
      "An elegant and floral Champagne with flavors of citrus, peach, and brioche. Delicate with a creamy finish.",
    tags: ["citrus", "peach", "brioche", "floral"],
    criticScore: 95,
    grape: "Chardonnay",
    avgPrice: 180,
    img: "https://example.com/images/perrierjouet.jpg",
    linkToPurchase: "https://example.com/purchase/perrierjouet",
  },
  {
    name: "Gaja Barbaresco",
    category: "Red",
    year: 2013,
    region: "Piedmont",
    winery: "Gaja",
    description:
      "A complex and refined wine with flavors of cherry, rose, and spice. Medium-bodied with a long, elegant finish.",
    tags: ["cherry", "rose", "spice", "refined"],
    criticScore: 96,
    grape: "Nebbiolo",
    avgPrice: 200,
    img: "https://example.com/images/gaja.jpg",
    linkToPurchase: "https://example.com/purchase/gaja",
  },
  {
    name: "Dr. Loosen Wehlener Sonnenuhr Riesling Spatlese",
    category: "White",
    year: 2016,
    region: "Mosel",
    winery: "Dr. Loosen",
    description:
      "A sweet and aromatic wine with flavors of peach, honey, and mineral notes. Light-bodied with a refreshing finish.",
    tags: ["peach", "honey", "mineral", "aromatic"],
    criticScore: 94,
    grape: "Riesling",
    avgPrice: 35,
    img: "https://example.com/images/drloosen.jpg",
    linkToPurchase: "https://example.com/purchase/drloosen",
  },
  {
    name: "Chateau Ste. Michelle Eroica Riesling",
    category: "White",
    year: 2018,
    region: "Washington",
    winery: "Chateau Ste. Michelle",
    description:
      "A crisp and vibrant wine with flavors of lime, green apple, and slate. Light-bodied with a clean, refreshing finish.",
    tags: ["lime", "green apple", "slate", "vibrant"],
    criticScore: 91,
    grape: "Riesling",
    avgPrice: 20,
    img: "https://example.com/images/eroica.jpg",
    linkToPurchase: "https://example.com/purchase/eroica",
  },
  {
    name: "Veuve Clicquot La Grande Dame",
    category: "Sparkling",
    year: 2008,
    region: "Champagne",
    winery: "Veuve Clicquot",
    description:
      "A sophisticated and elegant Champagne with flavors of citrus, almond, and brioche. Delicate with a creamy finish.",
    tags: ["citrus", "almond", "brioche", "elegant"],
    criticScore: 97,
    grape: "Pinot Noir",
    avgPrice: 220,
    img: "https://example.com/images/veuvecliquot.jpg",
    linkToPurchase: "https://example.com/purchase/veuvecliquot",
  },
  {
    name: "Torres Mas La Plana",
    category: "Red",
    year: 2014,
    region: "Penedes",
    winery: "Torres",
    description:
      "A powerful and full-bodied wine with flavors of black cherry, tobacco, and oak. Long, smooth finish.",
    tags: ["black cherry", "tobacco", "oak", "full-bodied"],
    criticScore: 94,
    grape: "Cabernet Sauvignon",
    avgPrice: 50,
    img: "https://example.com/images/maslaplana.jpg",
    linkToPurchase: "https://example.com/purchase/maslaplana",
  },
  {
    name: "Kendall-Jackson Vintner's Reserve Chardonnay",
    category: "White",
    year: 2019,
    region: "California",
    winery: "Kendall-Jackson",
    description:
      "A rich and creamy wine with flavors of tropical fruit, vanilla, and butter. Medium-bodied with a smooth finish.",
    tags: ["tropical fruit", "vanilla", "butter", "creamy"],
    criticScore: 90,
    grape: "Chardonnay",
    avgPrice: 15,
    img: "https://example.com/images/kendalljackson.jpg",
    linkToPurchase: "https://example.com/purchase/kendalljackson",
  },
  {
    name: "Bodegas Muga Prado Enea Gran Reserva",
    category: "Red",
    year: 2011,
    region: "Rioja",
    winery: "Bodegas Muga",
    description:
      "A complex and balanced wine with flavors of dark berries, leather, and tobacco. Full-bodied with a long, smooth finish.",
    tags: ["dark berries", "leather", "tobacco", "balanced"],
    criticScore: 95,
    grape: "Tempranillo",
    avgPrice: 80,
    img: "https://example.com/images/pradoenea.jpg",
    linkToPurchase: "https://example.com/purchase/pradoenea",
  },
  {
    name: "Ridge Monte Bello",
    category: "Red",
    year: 2013,
    region: "California",
    winery: "Ridge Vineyards",
    description:
      "An intense and structured wine with flavors of blackberry, cassis, and graphite. Full-bodied with a long, powerful finish.",
    tags: ["blackberry", "cassis", "graphite", "structured"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 180,
    img: "https://example.com/images/montebello.jpg",
    linkToPurchase: "https://example.com/purchase/montebello",
  },
  {
    name: "Chateau Haut-Brion",
    category: "Red",
    year: 2014,
    region: "Bordeaux",
    winery: "Chateau Haut-Brion",
    description:
      "A refined and elegant wine with flavors of blackcurrant, tobacco, and cedar. Full-bodied with a smooth, long finish.",
    tags: ["blackcurrant", "tobacco", "cedar", "elegant"],
    criticScore: 98,
    grape: "Cabernet Sauvignon",
    avgPrice: 550,
    img: "https://example.com/images/hautbrion.jpg",
    linkToPurchase: "https://example.com/purchase/hautbrion",
  },

  {
    name: "Egon Müller Scharzhofberger Riesling Auslese",
    category: "White",
    year: 2018,
    region: "Mosel",
    winery: "Egon Müller",
    description:
      "A sweet and aromatic wine with flavors of peach, honey, and floral notes. Light-bodied with a refreshing finish.",
    tags: ["peach", "honey", "floral", "aromatic"],
    criticScore: 97,
    grape: "Riesling",
    avgPrice: 300,
    img: "https://example.com/images/scharzhofberger.jpg",
    linkToPurchase: "https://example.com/purchase/scharzhofberger",
  },

  {
    name: "Gosset Grand Blanc de Blancs",
    category: "Sparkling",
    year: 2012,
    region: "Champagne",
    winery: "Gosset",
    description:
      "A sophisticated and elegant Champagne with flavors of citrus, almond, and brioche. Delicate with a creamy finish.",
    tags: ["citrus", "almond", "brioche", "elegant"],
    criticScore: 94,
    grape: "Chardonnay",
    avgPrice: 90,
    img: "https://example.com/images/gosset.jpg",
    linkToPurchase: "https://example.com/purchase/gosset",
  },
  {
    name: "Chateau de Beaucastel Chateauneuf-du-Pape",
    category: "Red",
    year: 2015,
    region: "Rhone Valley",
    winery: "Chateau de Beaucastel",
    description:
      "A robust and full-bodied wine with flavors of black cherry, licorice, and spice. Long, smooth finish.",
    tags: ["black cherry", "licorice", "spice", "robust"],
    criticScore: 97,
    grape: "Grenache",
    avgPrice: 100,
    img: "https://example.com/images/beaucastel.jpg",
    linkToPurchase: "https://example.com/purchase/beaucastel",
  },
  {
    name: "Quinta do Noval Nacional Vintage Port",
    category: "Dessert",
    year: 2011,
    region: "Douro",
    winery: "Quinta do Noval",
    description:
      "A rich and intense wine with flavors of black fruit, chocolate, and spice. Full-bodied with a long, sweet finish.",
    tags: ["black fruit", "chocolate", "spice", "intense"],
    criticScore: 98,
    grape: "Touriga Nacional",
    avgPrice: 700,
    img: "https://example.com/images/noval.jpg",
    linkToPurchase: "https://example.com/purchase/noval",
  },
  {
    name: "Domaine de la Romanée-Conti Montrachet",
    category: "White",
    year: 2017,
    region: "Burgundy",
    winery: "Domaine de la Romanée-Conti",
    description:
      "An exquisite and complex wine with flavors of citrus, hazelnut, and mineral notes. Medium-bodied with a long, elegant finish.",
    tags: ["citrus", "hazelnut", "mineral", "complex"],
    criticScore: 99,
    grape: "Chardonnay",
    avgPrice: 3000,
    img: "https://example.com/images/montrachet.jpg",
    linkToPurchase: "https://example.com/purchase/montrachet",
  },
  {
    name: "Clos de la Roche Grand Cru",
    category: "Red",
    year: 2016,
    region: "Burgundy",
    winery: "Domaine Dujac",
    description:
      "A rich and elegant wine with flavors of black cherry, earth, and spice. Full-bodied with a long, smooth finish.",
    tags: ["black cherry", "earth", "spice", "elegant"],
    criticScore: 96,
    grape: "Pinot Noir",
    avgPrice: 400,
    img: "https://example.com/images/closdelaroche.jpg",
    linkToPurchase: "https://example.com/purchase/closdelaroche",
  },

  {
    name: "Pol Roger Sir Winston Churchill",
    category: "Sparkling",
    year: 2008,
    region: "Champagne",
    winery: "Pol Roger",
    description:
      "A sophisticated and refined Champagne with flavors of brioche, citrus, and white flowers. Delicate with a creamy finish.",
    tags: ["brioche", "citrus", "white flowers", "refined"],
    criticScore: 98,
    grape: "Chardonnay",
    avgPrice: 250,
    img: "https://example.com/images/polroger.jpg",
    linkToPurchase: "https://example.com/purchase/polroger",
  },

  {
    name: "La Rioja Alta Gran Reserva 904",
    category: "Red",
    year: 2010,
    region: "Rioja",
    winery: "La Rioja Alta",
    description:
      "A complex and elegant wine with flavors of red berries, leather, and spice. Full-bodied with a long, smooth finish.",
    tags: ["red berries", "leather", "spice", "complex"],
    criticScore: 95,
    grape: "Tempranillo",
    avgPrice: 65,
    img: "https://example.com/images/lariojaalta.jpg",
    linkToPurchase: "https://example.com/purchase/lariojaalta",
  },
  {
    name: "Joseph Drouhin Marquis de Laguiche Montrachet",
    category: "White",
    year: 2016,
    region: "Burgundy",
    winery: "Joseph Drouhin",
    description:
      "An exquisite and rich wine with flavors of citrus, almond, and mineral notes. Medium-bodied with a long, elegant finish.",
    tags: ["citrus", "almond", "mineral", "rich"],
    criticScore: 97,
    grape: "Chardonnay",
    avgPrice: 900,
    img: "https://example.com/images/laguichemontrachet.jpg",
    linkToPurchase: "https://example.com/purchase/laguichemontrachet",
  },

  {
    name: "Domaine Zind-Humbrecht Clos Windsbuhl Riesling",
    category: "White",
    year: 2016,
    region: "Alsace",
    winery: "Domaine Zind-Humbrecht",
    description:
      "A crisp and aromatic wine with flavors of green apple, citrus, and mineral notes. Light-bodied with a refreshing finish.",
    tags: ["green apple", "citrus", "mineral", "aromatic"],
    criticScore: 94,
    grape: "Riesling",
    avgPrice: 70,
    img: "https://example.com/images/zindhumbrecht.jpg",
    linkToPurchase: "https://example.com/purchase/zindhumbrecht",
  },
  {
    name: "Chateau Leoville Las Cases",
    category: "Red",
    year: 2014,
    region: "Bordeaux",
    winery: "Chateau Leoville Las Cases",
    description:
      "A powerful and structured wine with flavors of blackcurrant, tobacco, and cedar. Full-bodied with a long, smooth finish.",
    tags: ["blackcurrant", "tobacco", "cedar", "structured"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 200,
    img: "https://example.com/images/leovillelascases.jpg",
    linkToPurchase: "https://example.com/purchase/leovillelascases",
  },
  {
    name: "Chateau Palmer",
    category: "Red",
    year: 2012,
    region: "Bordeaux",
    winery: "Chateau Palmer",
    description:
      "An opulent and full-bodied wine with flavors of blackberry, plum, and cedar. Rich with a long, smooth finish.",
    tags: ["blackberry", "plum", "cedar", "opulent"],
    criticScore: 95,
    grape: "Merlot",
    avgPrice: 220,
    img: "https://example.com/images/chateaupalmer.jpg",
    linkToPurchase: "https://example.com/purchase/chateaupalmer",
  },
  {
    name: "Kongsgaard Chardonnay",
    category: "White",
    year: 2017,
    region: "California",
    winery: "Kongsgaard",
    description:
      "A rich and full-bodied wine with flavors of ripe pear, apple, and toasted hazelnut. Creamy with a long, elegant finish.",
    tags: ["ripe pear", "apple", "toasted hazelnut", "full-bodied"],
    criticScore: 96,
    grape: "Chardonnay",
    avgPrice: 150,
    img: "https://example.com/images/kongsgaard.jpg",
    linkToPurchase: "https://example.com/purchase/kongsgaard",
  },
  {
    name: "Domaine Leroy Richebourg Grand Cru",
    category: "Red",
    year: 2013,
    region: "Burgundy",
    winery: "Domaine Leroy",
    description:
      "An exquisite and complex wine with flavors of dark cherry, earth, and spice. Full-bodied with a long, velvety finish.",
    tags: ["dark cherry", "earth", "spice", "complex"],
    criticScore: 98,
    grape: "Pinot Noir",
    avgPrice: 1500,
    img: "https://example.com/images/leroyrichebourg.jpg",
    linkToPurchase: "https://example.com/purchase/leroyrichebourg",
  },
  {
    name: "Chateau Rayas Chateauneuf-du-Pape",
    category: "Red",
    year: 2015,
    region: "Rhone Valley",
    winery: "Chateau Rayas",
    description:
      "A refined and elegant wine with flavors of red berries, herbs, and spice. Medium-bodied with a long, smooth finish.",
    tags: ["red berries", "herbs", "spice", "elegant"],
    criticScore: 97,
    grape: "Grenache",
    avgPrice: 700,
    img: "https://example.com/images/chateaurayas.jpg",
    linkToPurchase: "https://example.com/purchase/chateaurayas",
  },
  {
    name: "Krug Grande Cuvee",
    category: "Sparkling",
    year: 2016,
    region: "Champagne",
    winery: "Krug",
    description:
      "A luxurious and refined Champagne with flavors of brioche, citrus, and almond. Delicate with a creamy finish.",
    tags: ["brioche", "citrus", "almond", "luxurious"],
    criticScore: 97,
    grape: "Pinot Noir",
    avgPrice: 250,
    img: "https://example.com/images/krug.jpg",
    linkToPurchase: "https://example.com/purchase/krug",
  },
  {
    name: "Domaine Weinbach Riesling",
    category: "White",
    year: 2018,
    region: "Alsace",
    winery: "Domaine Weinbach",
    description:
      "A crisp and aromatic wine with flavors of green apple, citrus, and floral notes. Light-bodied with a refreshing finish.",
    tags: ["green apple", "citrus", "floral", "aromatic"],
    criticScore: 94,
    grape: "Riesling",
    avgPrice: 50,
    img: "https://example.com/images/weinbachriesling.jpg",
    linkToPurchase: "https://example.com/purchase/weinbachriesling",
  },

  {
    name: "Chateau Beaucastel Chateauneuf-du-Pape",
    category: "Red",
    year: 2017,
    region: "Rhone Valley",
    winery: "Chateau Beaucastel",
    description:
      "A complex and elegant wine with flavors of red fruit, earth, and spice. Medium-bodied with a long, smooth finish.",
    tags: ["red fruit", "earth", "spice", "complex"],
    criticScore: 95,
    grape: "Grenache",
    avgPrice: 80,
    img: "https://example.com/images/beaucastel.jpg",
    linkToPurchase: "https://example.com/purchase/beaucastel",
  },
  {
    name: "Guigal Cote Rotie La Landonne",
    category: "Red",
    year: 2015,
    region: "Rhone Valley",
    winery: "E. Guigal",
    description:
      "A powerful and structured wine with flavors of dark fruit, leather, and spice. Full-bodied with a long, smooth finish.",
    tags: ["dark fruit", "leather", "spice", "structured"],
    criticScore: 98,
    grape: "Syrah",
    avgPrice: 350,
    img: "https://example.com/images/guigal.jpg",
    linkToPurchase: "https://example.com/purchase/guigal",
  },

  {
    name: "Chateau Pichon Longueville Comtesse de Lalande",
    category: "Red",
    year: 2012,
    region: "Bordeaux",
    winery: "Chateau Pichon Longueville Comtesse de Lalande",
    description:
      "A refined wine with flavors of blackcurrant, cedar, and tobacco. Medium-bodied with a long, elegant finish.",
    tags: ["blackcurrant", "cedar", "tobacco", "refined"],
    criticScore: 95,
    grape: "Cabernet Sauvignon",
    avgPrice: 180,
    img: "https://example.com/images/pichon.jpg",
    linkToPurchase: "https://example.com/purchase/pichon",
  },
  {
    name: "Caymus Special Selection",
    category: "Red",
    year: 2014,
    region: "Napa Valley",
    winery: "Caymus",
    description:
      "A rich and full-bodied wine with flavors of dark cherry, chocolate, and vanilla. Smooth with a long, luxurious finish.",
    tags: ["dark cherry", "chocolate", "vanilla", "rich"],
    criticScore: 96,
    grape: "Cabernet Sauvignon",
    avgPrice: 150,
    img: "https://example.com/images/caymus.jpg",
    linkToPurchase: "https://example.com/purchase/caymus",
  },
  {
    name: "Cayuse Vineyards Bionic Frog Syrah",
    category: "Red",
    year: 2015,
    region: "Washington",
    winery: "Cayuse Vineyards",
    description:
      "A bold and complex wine with flavors of dark fruit, olive, and pepper. Full-bodied with a long, intense finish.",
    tags: ["dark fruit", "olive", "pepper", "bold"],
    criticScore: 97,
    grape: "Syrah",
    avgPrice: 190,
    img: "https://example.com/images/cayuse.jpg",
    linkToPurchase: "https://example.com/purchase/cayuse",
  },

  {
    name: "Pio Cesare Barolo",
    category: "Red",
    year: 2013,
    region: "Piedmont",
    winery: "Pio Cesare",
    description:
      "A traditional wine with flavors of red cherry, rose, and tar. Medium-bodied with a long, elegant finish.",
    tags: ["red cherry", "rose", "tar", "traditional"],
    criticScore: 94,
    grape: "Nebbiolo",
    avgPrice: 70,
    img: "https://example.com/images/piocesare.jpg",
    linkToPurchase: "https://example.com/purchase/piocesare",
  },
  {
    name: "Kumeu River Maté's Vineyard Chardonnay",
    category: "White",
    year: 2017,
    region: "Auckland",
    winery: "Kumeu River",
    description:
      "A refined and elegant wine with flavors of citrus, peach, and oak. Medium-bodied with a long, smooth finish.",
    tags: ["citrus", "peach", "oak", "elegant"],
    criticScore: 95,
    grape: "Chardonnay",
    avgPrice: 50,
    img: "https://example.com/images/kumeuriver.jpg",
    linkToPurchase: "https://example.com/purchase/kumeuriver",
  },
  {
    name: "Penfolds Bin 707 Cabernet Sauvignon",
    category: "Red",
    year: 2015,
    region: "South Australia",
    winery: "Penfolds",
    description:
      "A powerful and concentrated wine with flavors of blackcurrant, mint, and oak. Full-bodied with a long, rich finish.",
    tags: ["blackcurrant", "mint", "oak", "concentrated"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 350,
    img: "https://example.com/images/bin707.jpg",
    linkToPurchase: "https://example.com/purchase/bin707",
  },

  {
    name: "Domaine de la Romanee-Conti Montrachet",
    category: "White",
    year: 2014,
    region: "Burgundy",
    winery: "Domaine de la Romanee-Conti",
    description:
      "A legendary wine with flavors of citrus, pear, and hazelnut. Full-bodied with a long, complex finish.",
    tags: ["citrus", "pear", "hazelnut", "legendary"],
    criticScore: 99,
    grape: "Chardonnay",
    avgPrice: 3500,
    img: "https://example.com/images/montrachet.jpg",
    linkToPurchase: "https://example.com/purchase/montrachet",
  },
  {
    name: "Lapostolle Clos Apalta",
    category: "Red",
    year: 2013,
    region: "Colchagua Valley",
    winery: "Lapostolle",
    description:
      "A rich and luxurious wine with flavors of dark fruit, chocolate, and spice. Full-bodied with a long, smooth finish.",
    tags: ["dark fruit", "chocolate", "spice", "luxurious"],
    criticScore: 96,
    grape: "Carmenere",
    avgPrice: 120,
    img: "https://example.com/images/lapostolle.jpg",
    linkToPurchase: "https://example.com/purchase/lapostolle",
  },
  {
    name: "Guigal Condrieu La Doriane",
    category: "White",
    year: 2017,
    region: "Rhone Valley",
    winery: "E. Guigal",
    description:
      "A luxurious and aromatic wine with flavors of apricot, peach, and floral notes. Full-bodied with a long, smooth finish.",
    tags: ["apricot", "peach", "floral", "aromatic"],
    criticScore: 95,
    grape: "Viognier",
    avgPrice: 90,
    img: "https://example.com/images/guigalcondrieu.jpg",
    linkToPurchase: "https://example.com/purchase/guigalcondrieu",
  },
  {
    name: "Silver Oak Napa Valley Cabernet Sauvignon",
    category: "Red",
    year: 2014,
    region: "Napa Valley",
    winery: "Silver Oak",
    description:
      "A classic wine with flavors of blackberry, vanilla, and spice. Full-bodied with a long, smooth finish.",
    tags: ["blackberry", "vanilla", "spice", "classic"],
    criticScore: 94,
    grape: "Cabernet Sauvignon",
    avgPrice: 125,
    img: "https://example.com/images/silveroak.jpg",
    linkToPurchase: "https://example.com/purchase/silveroak",
  },
  {
    name: "Domaine Leflaive Puligny-Montrachet",
    category: "White",
    year: 2015,
    region: "Burgundy",
    winery: "Domaine Leflaive",
    description:
      "An elegant and refined wine with flavors of citrus, pear, and minerality. Medium-bodied with a long, smooth finish.",
    tags: ["citrus", "pear", "minerality", "refined"],
    criticScore: 95,
    grape: "Chardonnay",
    avgPrice: 200,
    img: "https://example.com/images/leflaive.jpg",
    linkToPurchase: "https://example.com/purchase/leflaive",
  },
  {
    name: "Joseph Phelps Insignia",
    category: "Red",
    year: 2013,
    region: "Napa Valley",
    winery: "Joseph Phelps",
    description:
      "A rich and complex wine with flavors of dark fruit, chocolate, and spice. Full-bodied with a long, luxurious finish.",
    tags: ["dark fruit", "chocolate", "spice", "complex"],
    criticScore: 96,
    grape: "Cabernet Sauvignon",
    avgPrice: 250,
    img: "https://example.com/images/insignia.jpg",
    linkToPurchase: "https://example.com/purchase/insignia",
  },
  {
    name: "Bollinger La Grande Annee",
    category: "Sparkling",
    year: 2008,
    region: "Champagne",
    winery: "Bollinger",
    description:
      "A luxurious and complex Champagne with flavors of brioche, citrus, and almond. Full-bodied with a long, elegant finish.",
    tags: ["brioche", "citrus", "almond", "complex"],
    criticScore: 96,
    grape: "Pinot Noir",
    avgPrice: 150,
    img: "https://example.com/images/bollinger.jpg",
    linkToPurchase: "https://example.com/purchase/bollinger",
  },
  {
    name: "Ornellaia",
    category: "Red",
    year: 2016,
    region: "Tuscany",
    winery: "Ornellaia",
    description:
      "A bold and intense wine with flavors of black cherry, plum, and tobacco. Full-bodied with a long, robust finish.",
    tags: ["black cherry", "plum", "tobacco", "bold"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 250,
    img: "https://example.com/images/ornellaia.jpg",
    linkToPurchase: "https://example.com/purchase/ornellaia",
  },

  {
    name: "Cloudy Bay Sauvignon Blanc",
    category: "White",
    year: 2018,
    region: "Marlborough",
    winery: "Cloudy Bay",
    description:
      "A vibrant and aromatic wine with flavors of passion fruit, lime, and green pepper. Light-bodied with a crisp, refreshing finish.",
    tags: ["passion fruit", "lime", "green pepper", "vibrant"],
    criticScore: 92,
    grape: "Sauvignon Blanc",
    avgPrice: 30,
    img: "https://example.com/images/cloudybay.jpg",
    linkToPurchase: "https://example.com/purchase/cloudybay",
  },
  {
    name: "Chateau Palmer",
    category: "Red",
    year: 2016,
    region: "Bordeaux",
    winery: "Chateau Palmer",
    description:
      "A refined and elegant wine with flavors of black cherry, plum, and spice. Medium-bodied with a long, smooth finish.",
    tags: ["black cherry", "plum", "spice", "elegant"],
    criticScore: 97,
    grape: "Merlot",
    avgPrice: 350,
    img: "https://example.com/images/palmer.jpg",
    linkToPurchase: "https://example.com/purchase/palmer",
  },
  {
    name: "Guigal La Turque",
    category: "Red",
    year: 2015,
    region: "Rhone Valley",
    winery: "E. Guigal",
    description:
      "A powerful and intense wine with flavors of black fruit, bacon, and pepper. Full-bodied with a long, robust finish.",
    tags: ["black fruit", "bacon", "pepper", "intense"],
    criticScore: 98,
    grape: "Syrah",
    avgPrice: 400,
    img: "https://example.com/images/laturque.jpg",
    linkToPurchase: "https://example.com/purchase/laturque",
  },

  {
    name: "Screaming Eagle",
    category: "Red",
    year: 2012,
    region: "Napa Valley",
    winery: "Screaming Eagle",
    description:
      "A legendary and highly sought-after wine with flavors of blackberry, currant, and oak. Full-bodied with a long, luxurious finish.",
    tags: ["blackberry", "currant", "oak", "legendary"],
    criticScore: 99,
    grape: "Cabernet Sauvignon",
    avgPrice: 3000,
    img: "https://example.com/images/screamingeagle.jpg",
    linkToPurchase: "https://example.com/purchase/screamingeagle",
  },
  {
    name: "Penfolds RWT Shiraz",
    category: "Red",
    year: 2014,
    region: "Barossa Valley",
    winery: "Penfolds",
    description:
      "A rich and full-bodied wine with flavors of blackberry, vanilla, and spice. Smooth with a long, velvety finish.",
    tags: ["blackberry", "vanilla", "spice", "rich"],
    criticScore: 95,
    grape: "Shiraz",
    avgPrice: 150,
    img: "https://example.com/images/rwtshiraz.jpg",
    linkToPurchase: "https://example.com/purchase/rwtshiraz",
  },
  {
    name: "Vietti Barolo Castiglione",
    category: "Red",
    year: 2016,
    region: "Piedmont",
    winery: "Vietti",
    description:
      "A traditional and elegant wine with flavors of red cherry, rose, and tar. Medium-bodied with a long, refined finish.",
    tags: ["red cherry", "rose", "tar", "elegant"],
    criticScore: 94,
    grape: "Nebbiolo",
    avgPrice: 70,
    img: "https://example.com/images/viettibarolo.jpg",
    linkToPurchase: "https://example.com/purchase/viettibarolo",
  },

  {
    name: "Graham's Vintage Port",
    category: "Dessert",
    year: 2011,
    region: "Douro Valley",
    winery: "Graham's",
    description:
      "A rich and luscious wine with flavors of black cherry, plum, and chocolate. Sweet with a long, velvety finish.",
    tags: ["black cherry", "plum", "chocolate", "luscious"],
    criticScore: 96,
    grape: "Touriga Nacional",
    avgPrice: 120,
    img: "https://example.com/images/grahams.jpg",
    linkToPurchase: "https://example.com/purchase/grahams",
  },
  {
    name: "Clos de Tart",
    category: "Red",
    year: 2015,
    region: "Burgundy",
    winery: "Clos de Tart",
    description:
      "A refined and elegant wine with flavors of red cherry, raspberry, and spice. Medium-bodied with a long, smooth finish.",
    tags: ["red cherry", "raspberry", "spice", "refined"],
    criticScore: 97,
    grape: "Pinot Noir",
    avgPrice: 350,
    img: "https://example.com/images/closdetart.jpg",
    linkToPurchase: "https://example.com/purchase/closdetart",
  },
  {
    name: "Chateau Lafleur",
    category: "Red",
    year: 2016,
    region: "Bordeaux",
    winery: "Chateau Lafleur",
    description:
      "A powerful and complex wine with flavors of blackcurrant, tobacco, and cedar. Full-bodied with a long, rich finish.",
    tags: ["blackcurrant", "tobacco", "cedar", "powerful"],
    criticScore: 98,
    grape: "Merlot",
    avgPrice: 1000,
    img: "https://example.com/images/lafleur.jpg",
    linkToPurchase: "https://example.com/purchase/lafleur",
  },
  {
    name: "Peter Michael Les Pavots",
    category: "Red",
    year: 2014,
    region: "Sonoma County",
    winery: "Peter Michael",
    description:
      "A rich and full-bodied wine with flavors of blackberry, chocolate, and spice. Smooth with a long, velvety finish.",
    tags: ["blackberry", "chocolate", "spice", "rich"],
    criticScore: 96,
    grape: "Cabernet Sauvignon",
    avgPrice: 200,
    img: "https://example.com/images/lespavots.jpg",
    linkToPurchase: "https://example.com/purchase/lespavots",
  },
  {
    name: "Torres Mas La Plana",
    category: "Red",
    year: 2015,
    region: "Penedes",
    winery: "Torres",
    description:
      "A bold and intense wine with flavors of black cherry, plum, and tobacco. Full-bodied with a long, robust finish.",
    tags: ["black cherry", "plum", "tobacco", "bold"],
    criticScore: 95,
    grape: "Cabernet Sauvignon",
    avgPrice: 60,
    img: "https://example.com/images/maslaplana.jpg",
    linkToPurchase: "https://example.com/purchase/maslaplana",
  },
  {
    name: "Clarendon Hills Astralis Syrah",
    category: "Red",
    year: 2010,
    region: "McLaren Vale",
    winery: "Clarendon Hills",
    description:
      "A powerful and intense wine with flavors of blackberry, plum, and spice. Full-bodied with a long, luxurious finish.",
    tags: ["blackberry", "plum", "spice", "intense"],
    criticScore: 97,
    grape: "Syrah",
    avgPrice: 350,
    img: "https://example.com/images/astralis.jpg",
    linkToPurchase: "https://example.com/purchase/astralis",
  },

  {
    name: "Shafer Hillside Select Cabernet Sauvignon",
    category: "Red",
    year: 2013,
    region: "Napa Valley",
    winery: "Shafer Vineyards",
    description:
      "A rich and full-bodied wine with flavors of blackberry, chocolate, and spice. Smooth with a long, luxurious finish.",
    tags: ["blackberry", "chocolate", "spice", "full-bodied"],
    criticScore: 98,
    grape: "Cabernet Sauvignon",
    avgPrice: 300,
    img: "https://example.com/images/shaferhillside.jpg",
    linkToPurchase: "https://example.com/purchase/shaferhillside",
  },
  {
    name: "Domaine de la Romanee-Conti Echezeaux",
    category: "Red",
    year: 2014,
    region: "Burgundy",
    winery: "Domaine de la Romanee-Conti",
    description:
      "An elegant and complex wine with flavors of red cherry, raspberry, and spice. Medium-bodied with a long, refined finish.",
    tags: ["red cherry", "raspberry", "spice", "elegant"],
    criticScore: 97,
    grape: "Pinot Noir",
    avgPrice: 1200,
    img: "https://example.com/images/echezeaux.jpg",
    linkToPurchase: "https://example.com/purchase/echezeaux",
  },
  {
    name: "Cheval Blanc",
    category: "Red",
    year: 1947,
    region: "Bordeaux",
    winery: "Château Cheval Blanc",
    description:
      "An exceptional vintage with rich, complex flavors of dark fruit, leather, and tobacco. Full-bodied with a velvety finish.",
    tags: ["dark fruit", "leather", "tobacco", "velvety"],
    criticScore: 100,
    grape: "Merlot",
    avgPrice: 5000,
    img: "https://example.com/images/cheval_blanc.jpg",
    linkToPurchase: "https://example.com/purchase/cheval_blanc",
  },
  {
    name: "Screaming Eagle",
    category: "Red",
    year: 1992,
    region: "Napa Valley",
    winery: "Screaming Eagle",
    description:
      "A cult classic with intense aromas of blackcurrant, cherry, and graphite. Powerful and concentrated with a long finish.",
    tags: ["blackcurrant", "cherry", "graphite", "concentrated"],
    criticScore: 98,
    grape: "Cabernet Sauvignon",
    avgPrice: 3000,
    img: "https://example.com/images/screaming_eagle.jpg",
    linkToPurchase: "https://example.com/purchase/screaming_eagle",
  },
  {
    name: "Romanée-Conti",
    category: "Red",
    year: 1945,
    region: "Burgundy",
    winery: "Domaine de la Romanée-Conti",
    description:
      "A legendary wine with complex layers of red fruit, spices, and earth. Elegant and harmonious with a long, persistent finish.",
    tags: ["red fruit", "spices", "earth", "elegant"],
    criticScore: 100,
    grape: "Pinot Noir",
    avgPrice: 20000,
    img: "https://example.com/images/romanee_conti.jpg",
    linkToPurchase: "https://example.com/purchase/romanee_conti",
  },
  {
    name: "Château d'Yquem",
    category: "Dessert",
    year: 1811,
    region: "Bordeaux",
    winery: "Château d'Yquem",
    description:
      "A rare vintage with flavors of honey, apricot, and caramel. Rich and luscious with a remarkable balance of sweetness and acidity.",
    tags: ["honey", "apricot", "caramel", "luscious"],
    criticScore: 99,
    grape: "Sémillon",
    avgPrice: 10000,
    img: "https://example.com/images/chateau_dyquem.jpg",
    linkToPurchase: "https://example.com/purchase/chateau_dyquem",
  },
  {
    name: "Château Lafite",
    category: "Red",
    year: 1787,
    region: "Bordeaux",
    winery: "Château Lafite Rothschild",
    description:
      "A historic wine with notes of leather, dried fruit, and spices. Smooth and well-integrated with a long, elegant finish.",
    tags: ["leather", "dried fruit", "spices", "elegant"],
    criticScore: 97,
    grape: "Cabernet Sauvignon",
    avgPrice: 20000,
    img: "https://example.com/images/chateau_lafite.jpg",
    linkToPurchase: "https://example.com/purchase/chateau_lafite",
  },
  {
    name: "Mouton-Rothschild",
    category: "Red",
    year: 1945,
    region: "Bordeaux",
    winery: "Château Mouton Rothschild",
    description:
      "A celebrated vintage with flavors of cassis, tobacco, and cedar. Powerful and structured with a long, complex finish.",
    tags: ["cassis", "tobacco", "cedar", "structured"],
    criticScore: 100,
    grape: "Cabernet Sauvignon",
    avgPrice: 5000,
    img: "https://example.com/images/mouton_rothschild.jpg",
    linkToPurchase: "https://example.com/purchase/mouton_rothschild",
  },
  {
    name: "Penfolds Block 42 Kalimna Cabernet Sauvignon",
    category: "Red",
    year: 2004,
    region: "South Australia",
    winery: "Penfolds",
    description:
      "A rare and iconic wine with intense flavors of blackcurrant, chocolate, and mint. Full-bodied with a long, persistent finish.",
    tags: ["blackcurrant", "chocolate", "mint", "full-bodied"],
    criticScore: 99,
    grape: "Cabernet Sauvignon",
    avgPrice: 8000,
    img: "https://example.com/images/penfolds_block42.jpg",
    linkToPurchase: "https://example.com/purchase/penfolds_block42",
  },
  {
    name: "Château Le Pin",
    category: "Red",
    year: 2000,
    region: "Bordeaux",
    winery: "Château Le Pin",
    description:
      "A luxurious wine with flavors of plum, chocolate, and truffle. Velvety texture with a long, seductive finish.",
    tags: ["plum", "chocolate", "truffle", "seductive"],
    criticScore: 98,
    grape: "Merlot",
    avgPrice: 6000,
    img: "https://example.com/images/chateau_lepin.jpg",
    linkToPurchase: "https://example.com/purchase/chateau_lepin",
  },
  {
    name: "Domaine Leroy Musigny Grand Cru",
    category: "Red",
    year: 1996,
    region: "Burgundy",
    winery: "Domaine Leroy",
    description:
      "An exquisite wine with flavors of red berries, spices, and floral notes. Elegant and refined with a long, harmonious finish.",
    tags: ["red berries", "spices", "floral", "refined"],
    criticScore: 99,
    grape: "Pinot Noir",
    avgPrice: 7000,
    img: "https://example.com/images/leroy_musigny.jpg",
    linkToPurchase: "https://example.com/purchase/leroy_musigny",
  },
  {
    name: "Domaine de la Romanée-Conti Romanée-Conti Grand Cru",
    category: "Red",
    year: 2005,
    region: "Burgundy",
    winery: "Domaine de la Romanée-Conti",
    description:
      "A masterpiece with flavors of cherry, earth, and spices. Silky texture with a long, elegant finish.",
    tags: ["cherry", "earth", "spices", "silky"],
    criticScore: 100,
    grape: "Pinot Noir",
    avgPrice: 12000,
    img: "https://example.com/images/romanee_conti_grand_cru.jpg",
    linkToPurchase: "https://example.com/purchase/romanee_conti_grand_cru",
  },
  {
    name: "Château Margaux",
    category: "Red",
    year: 1990,
    region: "Bordeaux",
    winery: "Château Margaux",
    description:
      "A legendary wine with flavors of blackcurrant, truffle, and graphite. Full-bodied with a silky, long finish.",
    tags: ["blackcurrant", "truffle", "graphite", "silky"],
    criticScore: 99,
    grape: "Cabernet Sauvignon",
    avgPrice: 8000,
    img: "https://example.com/images/chateau_margaux_1990.jpg",
    linkToPurchase: "https://example.com/purchase/chateau_margaux_1990",
  },
  {
    name: "Château Latour",
    category: "Red",
    year: 1982,
    region: "Bordeaux",
    winery: "Château Latour",
    description:
      "An exceptional vintage with notes of black fruit, cedar, and tobacco. Dense and powerful with a long, refined finish.",
    tags: ["black fruit", "cedar", "tobacco", "dense"],
    criticScore: 100,
    grape: "Cabernet Sauvignon",
    avgPrice: 12000,
    img: "https://example.com/images/chateau_latour_1982.jpg",
    linkToPurchase: "https://example.com/purchase/chateau_latour_1982",
  },
  {
    name: "Domaine de la Romanée-Conti La Tâche",
    category: "Red",
    year: 1978,
    region: "Burgundy",
    winery: "Domaine de la Romanée-Conti",
    description:
      "A magnificent wine with complex aromas of red fruit, spices, and earthy notes. Elegant and balanced with a long finish.",
    tags: ["red fruit", "spices", "earthy", "balanced"],
    criticScore: 98,
    grape: "Pinot Noir",
    avgPrice: 18000,
    img: "https://example.com/images/la_tache_1978.jpg",
    linkToPurchase: "https://example.com/purchase/la_tache_1978",
  },
  {
    name: "Château Palmer",
    category: "Red",
    year: 1961,
    region: "Bordeaux",
    winery: "Château Palmer",
    description:
      "An iconic vintage with flavors of plum, tobacco, and leather. Rich and concentrated with a long, smooth finish.",
    tags: ["plum", "tobacco", "leather", "concentrated"],
    criticScore: 97,
    grape: "Merlot",
    avgPrice: 9000,
    img: "https://example.com/images/chateau_palmer_1961.jpg",
    linkToPurchase: "https://example.com/purchase/chateau_palmer_1961",
  },
  {
    name: "Dom Pérignon",
    category: "Sparkling",
    year: 1959,
    region: "Champagne",
    winery: "Moët & Chandon",
    description:
      "A vintage Champagne with fine bubbles and notes of citrus, brioche, and almond. Elegant and complex with a long finish.",
    tags: ["citrus", "brioche", "almond", "elegant"],
    criticScore: 98,
    grape: "Chardonnay",
    avgPrice: 6000,
    img: "https://example.com/images/dom_perignon_1959.jpg",
    linkToPurchase: "https://example.com/purchase/dom_perignon_1959",
  },
  {
    name: "Château Lafite Rothschild",
    category: "Red",
    year: 1953,
    region: "Bordeaux",
    winery: "Château Lafite Rothschild",
    description:
      "A classic wine with flavors of blackcurrant, cedar, and tobacco. Elegant and refined with a long, persistent finish.",
    tags: ["blackcurrant", "cedar", "tobacco", "refined"],
    criticScore: 99,
    grape: "Cabernet Sauvignon",
    avgPrice: 11000,
    img: "https://example.com/images/chateau_lafite_1953.jpg",
    linkToPurchase: "https://example.com/purchase/chateau_lafite_1953",
  },
  {
    name: "Château Cheval Blanc",
    category: "Red",
    year: 1947,
    region: "Bordeaux",
    winery: "Château Cheval Blanc",
    description:
      "An extraordinary vintage with rich, opulent flavors of dark fruit, leather, and spice. Full-bodied with a velvety finish.",
    tags: ["dark fruit", "leather", "spice", "velvety"],
    criticScore: 100,
    grape: "Merlot",
    avgPrice: 20000,
    img: "https://example.com/images/cheval_blanc_1947.jpg",
    linkToPurchase: "https://example.com/purchase/cheval_blanc_1947",
  },
  {
    name: "Château Mouton Rothschild",
    category: "Red",
    year: 1945,
    region: "Bordeaux",
    winery: "Château Mouton Rothschild",
    description:
      "A legendary wine with flavors of cassis, tobacco, and cedar. Powerful and structured with a long, complex finish.",
    tags: ["cassis", "tobacco", "cedar", "structured"],
    criticScore: 100,
    grape: "Cabernet Sauvignon",
    avgPrice: 25000,
    img: "https://example.com/images/mouton_rothschild_1945.jpg",
    linkToPurchase: "https://example.com/purchase/mouton_rothschild_1945",
  },
  {
    name: "Giacomo Conterno Monfortino",
    category: "Red",
    year: 1961,
    region: "Piedmont",
    winery: "Giacomo Conterno",
    description:
      "A powerful and complex Barolo with flavors of cherry, tar, and roses. Full-bodied with a long, tannic finish.",
    tags: ["cherry", "tar", "roses", "tannic"],
    criticScore: 97,
    grape: "Nebbiolo",
    avgPrice: 7000,
    img: "https://example.com/images/monfortino_1961.jpg",
    linkToPurchase: "https://example.com/purchase/monfortino_1961",
  },
  {
    name: "Sassicaia",
    category: "Red",
    year: 1985,
    region: "Tuscany",
    winery: "Tenuta San Guido",
    description:
      "An iconic Super Tuscan with flavors of blackcurrant, tobacco, and cedar. Full-bodied with a long, smooth finish.",
    tags: ["blackcurrant", "tobacco", "cedar", "smooth"],
    criticScore: 98,
    grape: "Cabernet Sauvignon",
    avgPrice: 5000,
    img: "https://example.com/images/sassicaia_1985.jpg",
    linkToPurchase: "https://example.com/purchase/sassicaia_1985",
  },
];
module.exports = wines;
